"""Raw food catalog data — single source of truth for labels and nutrition fallbacks."""
from __future__ import annotations

from typing import Dict, List

from app.schemas.cv_schemas import MacroNutrients

LABEL_VI_OVERRIDES: Dict[str, str] = {'banh_da_do': 'Bánh đa đỏ (Hải Phòng)',
 'banh_mi': 'Bánh mì',
 'banh_trang': 'Bánh tráng',
 'bap_cai': 'Bắp cải',
 'bau': 'Quả bầu',
 'bi_do': 'Bí đỏ',
 'bi_xanh': 'Bí đao (Bí xanh)',
 'bong_bi': 'Bông bí',
 'bong_cai_xanh': 'Bông cải xanh (Súp lơ)',
 'bong_dien_dien': 'Bông điên điển',
 'bong_sung': 'Bông súng',
 'bot_cu_nang': 'Bột củ năng',
 'bot_gao': 'Bột gạo',
 'bot_nang': 'Bột năng',
 'bot_nep': 'Bột nếp',
 'bun': 'Bún tươi',
 'ca_chua': 'Cà chua',
 'ca_kho': 'Cá khô (sặc/dứa)',
 'ca_loc': 'Cá lóc (Cá quả)',
 'ca_ro': 'Cá rô',
 'ca_rot': 'Cà rốt',
 'ca_tre': 'Cá trê',
 'cai_cuc': 'Cải cúc (Tần ô)',
 'cai_ngot': 'Cải ngọt',
 'cai_thao': 'Cải thảo',
 'cai_xanh': 'Cải xanh',
 'chanh': 'Quả chanh',
 'cua_dong': 'Cua đồng (làm riêu cua)',
 'dau_den': 'Đậu đen',
 'dau_do': 'Đậu đỏ',
 'dau_hu': 'Đậu hũ (Đậu phụ)',
 'dau_oliu': 'Dầu ô liu',
 'dau_phong': 'Đậu phộng (Lạc)',
 'dau_xanh': 'Đậu xanh',
 'doc': 'Quả dọc',
 'dua_leo': 'Dưa leo (Dưa chuột)',
 'ech': 'Thịt ếch',
 'gao_lut': 'Gạo lứt',
 'gao_nep': 'Gạo nếp',
 'gao_te': 'Gạo tẻ',
 'gia_do': 'Giá đỗ',
 'giam_bong_me': 'Giấm bỗng / Giấm mẻ',
 'gung': 'Gừng',
 'hanh': 'Hành củ',
 'hanh_la': 'Hành lá',
 'hanh_tay': 'Hành tây',
 'hat_dieu': 'Hạt điều',
 'hat_tieu': 'Hạt tiêu',
 'he': 'Lá hẹ',
 'hen': 'Hến',
 'hoa_thien_ly': 'Hoa thiên lý',
 'hu_tieu': 'Hủ tiếu',
 'hung_que': 'Húng quế (Húng chó)',
 'khe_chua': 'Khế chua',
 'kho_qua': 'Khổ qua (Mướp đắng)',
 'khoai_lang': 'Khoai lang',
 'khoai_tay': 'Khoai tây',
 'kinh_gioi': 'Rau kinh giới',
 'la_lot': 'Lá lốt',
 'lap_xuong': 'Lạp xưởng',
 'luon': 'Thịt lươn',
 'mam_ba_khia': 'Mắm ba khía',
 'mam_ca': 'Mắm cá (sặc/linh)',
 'mam_nem': 'Mắm nêm',
 'mam_ruoc': 'Mắm ruốc',
 'mam_tom': 'Mắm tôm',
 'mang_tre': 'Măng tre (Tươi/Khô)',
 'me': 'Quả me',
 'mien_dong': 'Miến dong',
 'muc_kho': 'Mực khô',
 'muop_huong': 'Mướp hương',
 'nghe': 'Nghệ',
 'ngheu': 'Nghêu (Ngao)',
 'ngo': 'Ngô (Bắp)',
 'ngo_gai': 'Ngò gai (Mùi tàu)',
 'ngo_ri': 'Rau mùi (Ngò rí)',
 'nuoc_cot_dua': 'Nước cốt dừa',
 'nuoc_mam': 'Nước mắm',
 'oc': 'Các loại ốc',
 'ot': 'Ớt',
 'pho': 'Bánh phở',
 'quat_tac': 'Quả quất (tắc)',
 'rau_cang_cua': 'Rau càng cua',
 'rau_dang': 'Rau đắng',
 'rau_den': 'Rau dền',
 'rau_mong_toi': 'Rau mồng tơi',
 'rau_mop': 'Rau móp',
 'rau_muong': 'Rau muống',
 'rau_ngo': 'Rau ngổ (Ngò ôm)',
 'rau_ngot': 'Rau ngót',
 'rau_ram': 'Rau răm',
 'rau_toai': 'Rau toại',
 'rieng': 'Riềng',
 'sa': 'Sả',
 'sau': 'Quả sấu',
 'so': 'Các loại sò',
 'su_hao': 'Su hào',
 'tai_chua': 'Tai chua',
 'tao_pho': 'Tào phớ',
 'thit_ba_chi': 'Thịt ba chỉ',
 'thit_bo': 'Thịt bò',
 'thit_ga': 'Thịt gà',
 'thit_heo': 'Thịt heo (Thịt lợn)',
 'thit_ngan': 'Thịt ngan',
 'thit_vit': 'Thịt vịt',
 'tia_to': 'Rau tía tô',
 'toi': 'Tỏi',
 'tom_dong': 'Tôm đồng',
 'tom_kho': 'Tôm khô',
 'tuong_hot_ban': 'Tương hột / Tương bần',
 'uc_ga': 'Ức gà tươi sống',
 'unknown': 'Không xác định',
 'xa_lach': 'Xà lách'}

KEY_ALIASES: Dict[str, str] = {'banh_da_do': 'banh_da_cua',
 'bap_cai': 'cai_bap',
 'cai_cuc': 'rau_cai_cuc',
 'cai_ngot': 'rau_cai_ngot',
 'cai_xanh': 'rau_cai_xanh',
 'chicken': 'ga_ta',
 'chicken_breast': 'uc_ga',
 'dau_hu': 'dau_hu_trang',
 'fish_sauce': 'nuoc_mam',
 'hanh': 'hanh_tim',
 'mang_tre': 'mang_tuoi',
 'nghe': 'nghe_tuoi',
 'pork_belly': 'thit_ba_chi',
 'rau_mong_toi': 'mong_toi',
 'rice': 'com',
 'soy_sauce': 'nuoc_tuong',
 'thit_bo': 'thit_bo_than',
 'thit_ga': 'ga_ta',
 'thit_heo': 'thit_ba_chi',
 'thit_ngan': 'ngan',
 'thit_vit': 'vit',
 'tom_dong': 'tom_dat',
 'tuong_hot_ban': 'tuong_ban',
 'white_rice': 'com'}

EN_ALIASES_EXTRA: Dict[str, List[str]] = {'bong_cai_xanh': ['broccoli', 'green broccoli'],
 'ca_chua': ['tomato', 'tomatoes'],
 'ga_ta': ['chicken', 'chicken meat', 'free range chicken'],
 'nuoc_mam': ['fish sauce'],
 'pho': ['pho noodle soup', 'vietnamese pho'],
 'rau_muong': ['water spinach', 'morning glory', 'kangkong'],
 'thit_ba_chi': ['pork belly', 'pork_belly', 'bacon pork'],
 'tom_su': ['tiger shrimp', 'black tiger shrimp', 'shrimp'],
 'uc_ga': ['chicken breast', 'chicken_breast', 'breast chicken']}

VIET_TO_USDA_QUERY: Dict[str, str] = {'banh_canh': 'thick rice noodle',
 'banh_da_cua': 'red rice noodle crab',
 'banh_hoi': 'thin rice vermicelli cake',
 'banh_pho': 'pho rice noodle',
 'banh_trang': 'rice paper wrapper',
 'bap_bo': 'beef shank',
 'bau': 'bottle gourd',
 'bi_do': 'pumpkin',
 'bi_xanh': 'winter melon wax gourd',
 'bot_banh_xeo': 'rice flour crispy pancake mix',
 'bot_chien_xu': 'breadcrumbs tempura',
 'bot_gao': 'rice flour',
 'bot_nang': 'tapioca starch',
 'bot_nep': 'glutinous rice flour',
 'bot_ngot': 'monosodium glutamate MSG',
 'bun': 'rice vermicelli noodle',
 'ca_bong': 'goby fish',
 'ca_chua': 'tomato',
 'ca_dieu_hong': 'tilapia red',
 'ca_loc': 'snakehead fish',
 'ca_ngu': 'tuna fish',
 'ca_nuc': 'round scad fish',
 'ca_phao': 'pea eggplant Thai',
 'ca_ro': 'climbing perch fish',
 'ca_rot': 'carrot',
 'ca_thu': 'mackerel fish',
 'ca_tim': 'eggplant aubergine',
 'ca_tre': 'catfish',
 'cai_bap': 'cabbage',
 'chao_do': 'red fermented tofu',
 'chao_trang': 'white fermented tofu',
 'chim_bo_cau': 'pigeon squab',
 'chuoi_chat': 'unripe green banana',
 'com': 'cooked white rice',
 'com_me': 'fermented rice',
 'cot_m': 'young sticky rice com',
 'cu_cai_trang': 'daikon white radish',
 'cu_nen': 'chinese shallot',
 'cu_san': 'jicama yambean',
 'cua_bien': 'blue swimming crab',
 'cua_dong': 'freshwater crab',
 'da_heo': 'pork skin rind',
 'dau_hao': 'oyster sauce',
 'dau_hu_chien': 'fried tofu',
 'dau_hu_trang': 'tofu soft white',
 'dau_mau_dieu': 'annatto oil',
 'dau_me': 'sesame oil',
 'dau_phong': 'peanut groundnut',
 'dau_xanh': 'mung bean',
 'dieu_ca': 'fish mint houttuynia',
 'dinh_huong': 'cloves spice',
 'doc_mung': 'taro stem Vietnamese',
 'dua_thom': 'pineapple',
 'duoi_bo': 'oxtail',
 'duong_cat': 'white sugar',
 'duong_phen': 'rock sugar',
 'duong_thot_not': 'palm sugar',
 'ga_ta': 'free range chicken',
 'gan_bo': 'beef tendon',
 'gao_nep': 'glutinous sticky rice',
 'gao_te': 'white rice',
 'ghe': 'mud crab',
 'gia_do': 'mung bean sprouts',
 'giam_gao': 'rice vinegar',
 'giam_nuoi': 'vinegar',
 'gio_song': 'fresh pork sausage paste',
 'gung': 'ginger root',
 'hanh_la': 'green onion scallion',
 'hanh_tay': 'onion',
 'hanh_tim': 'shallot',
 'hat_dieu': 'cashew nut',
 'hat_doi': 'Vietnamese wild pepper doi',
 'hat_mac_khen': 'Sichuan pepper Vietnamese',
 'hat_mui': 'coriander seed',
 'hat_nem': 'seasoning powder umami',
 'hen': 'freshwater mussel',
 'hoa_chuoi': 'banana blossom flower',
 'hoa_hoi': 'star anise spice',
 'hu_tieu': 'rice noodle hu tieu',
 'hung_lui': 'spearmint Vietnamese',
 'hung_que': 'Thai basil',
 'khe_chua': 'star fruit carambola',
 'kho_qua': 'bitter melon',
 'khoai_lang': 'sweet potato',
 'khoai_mon': 'taro root',
 'khoai_so': 'cocoyam coco yam',
 'khoai_tay': 'potato',
 'kinh_gioi': 'Vietnamese balm herb',
 'la_cach': 'Vietnamese herb la cach',
 'la_chanh': 'kaffir lime leaf',
 'la_dua': 'pandan leaf',
 'la_giang': 'sour leaf soup herb Vietnam',
 'la_lot': 'betel leaf',
 'la_mac_mat': 'litsea cubeba leaf',
 'long_heo': 'pork intestine',
 'luon': 'eel freshwater',
 'mam_ba_khia': 'fermented crab',
 'mam_ca_linh': 'fermented freshwater fish',
 'mam_ca_sac': 'fermented snakeskin fish',
 'mam_nem': 'fermented anchovy sauce',
 'mam_ruoc': 'fermented shrimp paste',
 'mam_tep': 'fermented shrimp',
 'mam_tom': 'shrimp paste',
 'mang_chua': 'pickled bamboo shoot sour',
 'mang_kho': 'dried bamboo shoot',
 'mang_tuoi': 'fresh bamboo shoot',
 'me_qua': 'tamarind',
 'me_vung': 'sesame seed',
 'mi_trung': 'egg noodle',
 'mien_dong': 'glass noodle mung bean',
 'mo_heo': 'lard',
 'moc_nhi': 'wood ear mushroom black fungus',
 'mong_gio': 'pig trotter',
 'mong_toi': 'Malabar spinach',
 'muc_la': 'squid flat',
 'muc_ong': 'squid tube',
 'muc_trung': 'squid with eggs',
 'muoi_ham': 'salt',
 'muoi_hat': 'salt',
 'muop_huong': 'luffa ridged gourd',
 'nam_bao_ngu': 'oyster mushroom',
 'nam_bo': 'beef brisket',
 'nam_huong': 'shiitake mushroom',
 'nam_kim_cham': 'enoki mushroom',
 'nam_rom': 'straw mushroom',
 'ngan': 'muscovy duck',
 'nghe_tuoi': 'fresh turmeric root',
 'ngheu': 'clam',
 'ngo_gai': 'culantro sawtooth herb',
 'ngo_ri': 'cilantro coriander leaves',
 'ngo_sen': 'lotus root',
 'nuoc_mam': 'fish sauce',
 'nuoc_mam_nhi': 'fish sauce premium',
 'nuoc_tuong': 'soy sauce',
 'oc_buou': 'golden apple snail',
 'ot_hiem': 'bird eye chili pepper',
 'ot_sung': 'horn chili pepper',
 'qua_doc': 'wild mangosteen sour',
 'qua_sau': 'hog plum spondias',
 'que_chi': 'cinnamon stick',
 'rau_cai_cuc': 'chrysanthemum greens',
 'rau_cai_ngot': 'baby Chinese cabbage',
 'rau_cai_thia': 'bok choy',
 'rau_cai_xanh': 'Chinese mustard greens',
 'rau_dang': 'bitter herb Vietnam',
 'rau_den': 'amaranth leaves',
 'rau_hung_cay': 'peppermint herb',
 'rau_muong': 'water spinach kangkong',
 'rau_ngo': 'Vietnamese herb ngo om',
 'rau_ngot': 'katuk sweet leaf',
 'rau_ram': 'Vietnamese coriander',
 'rieng': 'galangal',
 'sa': 'lemongrass',
 'so_huyet': 'blood cockle',
 'su_hao': 'kohlrabi',
 'su_su': 'chayote',
 'sung': 'fig',
 'suon_non': 'pork spare ribs',
 'tai_chua': 'garcinia cowa sour fruit',
 'tai_heo': 'pig ear',
 'tau_hu_ky': 'tofu skin yuba',
 'thao_qua': 'black cardamom',
 'thi_la': 'dill herb',
 'thit_ba_chi': 'pork belly',
 'thit_bo_than': 'beef sirloin',
 'thit_nac_dam': 'pork loin',
 'thit_nac_vai': 'pork shoulder',
 'tia_to': 'perilla leaf shiso',
 'tieu_den': 'black pepper',
 'tieu_so': 'white pepper',
 'tieu_xanh': 'fresh green pepper cluster',
 'toi': 'garlic',
 'tom_dat': 'white shrimp',
 'tom_su': 'black tiger shrimp',
 'tom_the': 'pacific white shrimp',
 'top_mo': 'pork crackling',
 'trung_bac_thao': 'century egg preserved',
 'trung_cut': 'quail egg',
 'trung_ga': 'chicken egg',
 'trung_muoi': 'salted duck egg',
 'trung_vit': 'duck egg',
 'trung_vit_lon': 'balut fertilized egg',
 'tuong_ban': 'fermented yellow soybean paste',
 'tuong_den': 'black bean sauce',
 'tuong_hot': 'fermented soybean sauce',
 'tuong_ot': 'chili sauce',
 'vit': 'duck meat',
 'xa_lach': 'lettuce',
 'xi_dau': 'soy sauce',
 'xoai_xanh': 'green unripe mango'}

FALLBACK_NUTRITION: Dict[str, MacroNutrients] = {
    "default":    MacroNutrients(calories_kcal=200, protein_g=8,  carbs_g=25, fat_g=8),
    "pizza":      MacroNutrients(calories_kcal=266, protein_g=11, carbs_g=33, fat_g=10),
    "sushi":      MacroNutrients(calories_kcal=143, protein_g=9,  carbs_g=19, fat_g=3),
    "ramen":      MacroNutrients(calories_kcal=436, protein_g=17, carbs_g=60, fat_g=14),
    "pho":        MacroNutrients(calories_kcal=215, protein_g=15, carbs_g=30, fat_g=4),
    "hamburger":  MacroNutrients(calories_kcal=295, protein_g=17, carbs_g=24, fat_g=14),
    "nuoc_mam":       MacroNutrients(calories_kcal=35,  protein_g=5.0, carbs_g=3.6, fat_g=0.0,  fiber_g=0.0),
    "nuoc_mam_nhi":   MacroNutrients(calories_kcal=40,  protein_g=6.0, carbs_g=3.8, fat_g=0.0,  fiber_g=0.0),
    "mam_tom":        MacroNutrients(calories_kcal=62,  protein_g=7.0, carbs_g=3.0, fat_g=1.5,  fiber_g=0.0),
    "mam_ruoc":       MacroNutrients(calories_kcal=55,  protein_g=6.0, carbs_g=2.0, fat_g=1.0,  fiber_g=0.0),
    "mam_nem":        MacroNutrients(calories_kcal=48,  protein_g=5.5, carbs_g=3.5, fat_g=0.8,  fiber_g=0.0),
    "mam_tep":        MacroNutrients(calories_kcal=50,  protein_g=5.0, carbs_g=3.0, fat_g=1.0,  fiber_g=0.0),
    "mam_ba_khia":    MacroNutrients(calories_kcal=60,  protein_g=7.5, carbs_g=1.0, fat_g=2.0,  fiber_g=0.0),
    "mam_ca_sac":     MacroNutrients(calories_kcal=110, protein_g=15.0,carbs_g=0.0, fat_g=5.0,  fiber_g=0.0),
    "mam_ca_linh":    MacroNutrients(calories_kcal=115, protein_g=14.0,carbs_g=0.0, fat_g=6.0,  fiber_g=0.0),
    "tuong_hot":      MacroNutrients(calories_kcal=100, protein_g=6.0, carbs_g=12.0,fat_g=3.0,  fiber_g=1.5),
    "tuong_ban":      MacroNutrients(calories_kcal=98,  protein_g=5.5, carbs_g=11.0,fat_g=3.0,  fiber_g=1.0),
    "tuong_den":      MacroNutrients(calories_kcal=94,  protein_g=4.5, carbs_g=15.0,fat_g=2.0,  fiber_g=0.5),
    "tuong_ot":       MacroNutrients(calories_kcal=56,  protein_g=1.0, carbs_g=12.0,fat_g=0.5,  fiber_g=0.8),
    "nuoc_tuong":     MacroNutrients(calories_kcal=53,  protein_g=8.1, carbs_g=4.9, fat_g=0.1,  fiber_g=0.0),
    "xi_dau":         MacroNutrients(calories_kcal=53,  protein_g=8.1, carbs_g=4.9, fat_g=0.1,  fiber_g=0.0),
    "giam_gao":       MacroNutrients(calories_kcal=18,  protein_g=0.0, carbs_g=0.9, fat_g=0.0,  fiber_g=0.0),
    "giam_nuoi":      MacroNutrients(calories_kcal=18,  protein_g=0.0, carbs_g=0.9, fat_g=0.0,  fiber_g=0.0),
    "com_me":         MacroNutrients(calories_kcal=65,  protein_g=1.5, carbs_g=14.0,fat_g=0.2,  fiber_g=0.0),
    "tai_chua":       MacroNutrients(calories_kcal=38,  protein_g=0.5, carbs_g=9.0, fat_g=0.2,  fiber_g=1.0),
    "qua_doc":        MacroNutrients(calories_kcal=42,  protein_g=0.5, carbs_g=10.0,fat_g=0.3,  fiber_g=0.8),
    "chao_trang":     MacroNutrients(calories_kcal=128, protein_g=9.0, carbs_g=4.0, fat_g=9.0,  fiber_g=0.5),
    "chao_do":        MacroNutrients(calories_kcal=132, protein_g=8.5, carbs_g=5.0, fat_g=9.5,  fiber_g=0.5),
    "dau_mau_dieu":   MacroNutrients(calories_kcal=884, protein_g=0.0, carbs_g=0.0, fat_g=100.0,fiber_g=0.0),
    "dau_me":         MacroNutrients(calories_kcal=884, protein_g=0.0, carbs_g=0.0, fat_g=100.0,fiber_g=0.0),
    "dau_hao":        MacroNutrients(calories_kcal=79,  protein_g=0.8, carbs_g=17.5,fat_g=0.3,  fiber_g=0.0),
    "mo_heo":         MacroNutrients(calories_kcal=900, protein_g=0.0, carbs_g=0.0, fat_g=100.0,fiber_g=0.0),
    "top_mo":         MacroNutrients(calories_kcal=540, protein_g=12.0,carbs_g=0.0, fat_g=55.0, fiber_g=0.0),
    "hanh_tim":       MacroNutrients(calories_kcal=72,  protein_g=2.5, carbs_g=16.8,fat_g=0.1,  fiber_g=3.2),
    "hanh_tay":       MacroNutrients(calories_kcal=40,  protein_g=1.1, carbs_g=9.3, fat_g=0.1,  fiber_g=1.7),
    "toi":            MacroNutrients(calories_kcal=149, protein_g=6.4, carbs_g=33.1,fat_g=0.5,  fiber_g=2.1),
    "gung":           MacroNutrients(calories_kcal=80,  protein_g=1.8, carbs_g=17.8,fat_g=0.8,  fiber_g=2.0),
    "sa":             MacroNutrients(calories_kcal=99,  protein_g=1.8, carbs_g=25.3,fat_g=0.5,  fiber_g=0.0),
    "rieng":          MacroNutrients(calories_kcal=63,  protein_g=1.0, carbs_g=15.0,fat_g=0.5,  fiber_g=0.0),
    "nghe_tuoi":      MacroNutrients(calories_kcal=80,  protein_g=2.0, carbs_g=17.0,fat_g=1.0,  fiber_g=2.0),
    "cu_nen":         MacroNutrients(calories_kcal=70,  protein_g=2.2, carbs_g=15.5,fat_g=0.2,  fiber_g=2.0),
    "hanh_la":        MacroNutrients(calories_kcal=32,  protein_g=1.8, carbs_g=7.3, fat_g=0.2,  fiber_g=2.6),
    "ngo_ri":         MacroNutrients(calories_kcal=23,  protein_g=2.1, carbs_g=3.7, fat_g=0.5,  fiber_g=2.8),
    "ngo_gai":        MacroNutrients(calories_kcal=25,  protein_g=2.0, carbs_g=4.0, fat_g=0.5,  fiber_g=2.5),
    "rau_ngo":        MacroNutrients(calories_kcal=26,  protein_g=2.0, carbs_g=4.5, fat_g=0.4,  fiber_g=2.0),
    "hung_que":       MacroNutrients(calories_kcal=22,  protein_g=3.2, carbs_g=2.7, fat_g=0.6,  fiber_g=1.6),
    "hung_lui":       MacroNutrients(calories_kcal=44,  protein_g=3.3, carbs_g=8.4, fat_g=0.7,  fiber_g=6.8),
    "tia_to":         MacroNutrients(calories_kcal=37,  protein_g=3.8, carbs_g=7.0, fat_g=0.1,  fiber_g=7.0),
    "kinh_gioi":      MacroNutrients(calories_kcal=20,  protein_g=1.5, carbs_g=4.0, fat_g=0.3,  fiber_g=1.5),
    "rau_ram":        MacroNutrients(calories_kcal=25,  protein_g=2.0, carbs_g=5.0, fat_g=0.2,  fiber_g=2.0),
    "dieu_ca":        MacroNutrients(calories_kcal=20,  protein_g=1.5, carbs_g=4.0, fat_g=0.2,  fiber_g=1.8),
    "thi_la":         MacroNutrients(calories_kcal=43,  protein_g=3.5, carbs_g=7.0, fat_g=1.1,  fiber_g=2.1),
    "rau_hung_cay":   MacroNutrients(calories_kcal=70,  protein_g=3.8, carbs_g=15.0,fat_g=0.9,  fiber_g=8.0),
    "la_lot":         MacroNutrients(calories_kcal=40,  protein_g=3.0, carbs_g=6.0, fat_g=1.0,  fiber_g=3.5),
    "la_chanh":       MacroNutrients(calories_kcal=30,  protein_g=1.5, carbs_g=6.0, fat_g=0.5,  fiber_g=3.0),
    "la_dua":         MacroNutrients(calories_kcal=85,  protein_g=2.0, carbs_g=20.0,fat_g=0.1,  fiber_g=3.0),
    "la_mac_mat":     MacroNutrients(calories_kcal=35,  protein_g=1.5, carbs_g=7.0, fat_g=0.5,  fiber_g=2.5),
    "la_cach":        MacroNutrients(calories_kcal=30,  protein_g=2.5, carbs_g=5.0, fat_g=0.5,  fiber_g=3.0),
    "la_giang":       MacroNutrients(calories_kcal=28,  protein_g=1.8, carbs_g=5.5, fat_g=0.3,  fiber_g=2.5),
    "ot_hiem":        MacroNutrients(calories_kcal=40,  protein_g=2.0, carbs_g=9.0, fat_g=0.4,  fiber_g=1.5),
    "ot_sung":        MacroNutrients(calories_kcal=35,  protein_g=1.5, carbs_g=8.0, fat_g=0.3,  fiber_g=1.2),
    "tieu_den":       MacroNutrients(calories_kcal=255, protein_g=10.4,carbs_g=64.8,fat_g=3.3,  fiber_g=25.3),
    "tieu_so":        MacroNutrients(calories_kcal=296, protein_g=10.4,carbs_g=68.6,fat_g=2.1,  fiber_g=26.2),
    "tieu_xanh":      MacroNutrients(calories_kcal=250, protein_g=10.0,carbs_g=62.0,fat_g=3.0,  fiber_g=24.0),
    "rau_muong":      MacroNutrients(calories_kcal=19,  protein_g=2.6, carbs_g=3.1, fat_g=0.2,  fiber_g=2.1),
    "rau_cai_xanh":   MacroNutrients(calories_kcal=22,  protein_g=2.2, carbs_g=4.0, fat_g=0.2,  fiber_g=1.8),
    "rau_cai_ngot":   MacroNutrients(calories_kcal=15,  protein_g=1.4, carbs_g=2.6, fat_g=0.2,  fiber_g=1.2),
    "rau_cai_cuc":    MacroNutrients(calories_kcal=22,  protein_g=1.6, carbs_g=4.2, fat_g=0.3,  fiber_g=2.5),
    "rau_cai_thia":   MacroNutrients(calories_kcal=13,  protein_g=1.5, carbs_g=2.2, fat_g=0.2,  fiber_g=1.0),
    "mong_toi":       MacroNutrients(calories_kcal=19,  protein_g=1.8, carbs_g=3.4, fat_g=0.3,  fiber_g=0.9),
    "rau_ngot":       MacroNutrients(calories_kcal=60,  protein_g=6.0, carbs_g=12.0,fat_g=0.5,  fiber_g=5.0),
    "xa_lach":        MacroNutrients(calories_kcal=15,  protein_g=1.4, carbs_g=2.9, fat_g=0.2,  fiber_g=1.3),
    "rau_dang":       MacroNutrients(calories_kcal=25,  protein_g=2.0, carbs_g=5.0, fat_g=0.2,  fiber_g=2.0),
    "cai_bap":        MacroNutrients(calories_kcal=25,  protein_g=1.3, carbs_g=5.8, fat_g=0.1,  fiber_g=2.5),
    "rau_den":        MacroNutrients(calories_kcal=23,  protein_g=2.5, carbs_g=4.0, fat_g=0.2,  fiber_g=2.2),
    "kho_qua":        MacroNutrients(calories_kcal=17,  protein_g=1.0, carbs_g=3.7, fat_g=0.2,  fiber_g=2.8),
    "bau":            MacroNutrients(calories_kcal=14,  protein_g=0.6, carbs_g=3.4, fat_g=0.0,  fiber_g=0.5),
    "bi_xanh":        MacroNutrients(calories_kcal=13,  protein_g=0.4, carbs_g=3.0, fat_g=0.2,  fiber_g=0.5),
    "bi_do":          MacroNutrients(calories_kcal=26,  protein_g=1.0, carbs_g=6.5, fat_g=0.1,  fiber_g=0.5),
    "muop_huong":     MacroNutrients(calories_kcal=20,  protein_g=1.2, carbs_g=4.4, fat_g=0.2,  fiber_g=0.5),
    "su_su":          MacroNutrients(calories_kcal=19,  protein_g=0.8, carbs_g=4.5, fat_g=0.1,  fiber_g=1.7),
    "ca_chua":        MacroNutrients(calories_kcal=18,  protein_g=0.9, carbs_g=3.9, fat_g=0.2,  fiber_g=1.2),
    "ca_phao":        MacroNutrients(calories_kcal=25,  protein_g=1.0, carbs_g=5.9, fat_g=0.2,  fiber_g=3.0),
    "ca_tim":         MacroNutrients(calories_kcal=25,  protein_g=1.0, carbs_g=5.9, fat_g=0.2,  fiber_g=3.0),
    "ca_rot":         MacroNutrients(calories_kcal=41,  protein_g=0.9, carbs_g=9.6, fat_g=0.2,  fiber_g=2.8),
    "cu_cai_trang":   MacroNutrients(calories_kcal=18,  protein_g=0.6, carbs_g=4.1, fat_g=0.1,  fiber_g=1.6),
    "su_hao":         MacroNutrients(calories_kcal=27,  protein_g=1.7, carbs_g=6.2, fat_g=0.1,  fiber_g=3.6),
    "khoai_tay":      MacroNutrients(calories_kcal=77,  protein_g=2.0, carbs_g=17.0,fat_g=0.1,  fiber_g=2.2),
    "khoai_lang":     MacroNutrients(calories_kcal=86,  protein_g=1.6, carbs_g=20.1,fat_g=0.1,  fiber_g=3.0),
    "khoai_mon":      MacroNutrients(calories_kcal=112, protein_g=1.5, carbs_g=26.5,fat_g=0.2,  fiber_g=4.1),
    "khoai_so":       MacroNutrients(calories_kcal=105, protein_g=1.4, carbs_g=24.8,fat_g=0.2,  fiber_g=3.5),
    "cu_san":         MacroNutrients(calories_kcal=38,  protein_g=0.7, carbs_g=8.8, fat_g=0.1,  fiber_g=4.9),
    "hoa_chuoi":      MacroNutrients(calories_kcal=37,  protein_g=1.6, carbs_g=9.0, fat_g=0.6,  fiber_g=5.7),
    "ngo_sen":        MacroNutrients(calories_kcal=74,  protein_g=2.6, carbs_g=17.2,fat_g=0.1,  fiber_g=4.9),
    "gia_do":         MacroNutrients(calories_kcal=30,  protein_g=3.0, carbs_g=5.9, fat_g=0.2,  fiber_g=1.8),
    "mang_tuoi":      MacroNutrients(calories_kcal=27,  protein_g=2.6, carbs_g=5.2, fat_g=0.3,  fiber_g=2.2),
    "mang_kho":       MacroNutrients(calories_kcal=260, protein_g=25.0,carbs_g=49.0,fat_g=3.0,  fiber_g=15.0),
    "mang_chua":      MacroNutrients(calories_kcal=22,  protein_g=2.0, carbs_g=4.5, fat_g=0.2,  fiber_g=2.0),
    "doc_mung":       MacroNutrients(calories_kcal=13,  protein_g=0.8, carbs_g=3.0, fat_g=0.1,  fiber_g=0.8),
    "nam_rom":        MacroNutrients(calories_kcal=22,  protein_g=3.0, carbs_g=4.0, fat_g=0.3,  fiber_g=1.0),
    "moc_nhi":        MacroNutrients(calories_kcal=25,  protein_g=1.5, carbs_g=6.8, fat_g=0.2,  fiber_g=6.5),
    "nam_huong":      MacroNutrients(calories_kcal=34,  protein_g=2.2, carbs_g=6.8, fat_g=0.5,  fiber_g=2.5),
    "nam_kim_cham":   MacroNutrients(calories_kcal=37,  protein_g=2.7, carbs_g=8.1, fat_g=0.3,  fiber_g=2.7),
    "nam_bao_ngu":    MacroNutrients(calories_kcal=33,  protein_g=3.3, carbs_g=6.1, fat_g=0.4,  fiber_g=2.3),
    "gao_te":         MacroNutrients(calories_kcal=365, protein_g=7.1, carbs_g=80.0,fat_g=0.7,  fiber_g=1.3),
    "gao_nep":        MacroNutrients(calories_kcal=360, protein_g=6.8, carbs_g=79.0,fat_g=0.6,  fiber_g=0.5),
    "com":            MacroNutrients(calories_kcal=130, protein_g=2.7, carbs_g=28.2,fat_g=0.3,  fiber_g=0.4),
    "cot_m":          MacroNutrients(calories_kcal=120, protein_g=3.5, carbs_g=25.0,fat_g=0.5,  fiber_g=0.5),
    "bun":            MacroNutrients(calories_kcal=109, protein_g=2.0, carbs_g=24.2,fat_g=0.2,  fiber_g=0.4),
    "banh_pho":       MacroNutrients(calories_kcal=109, protein_g=2.0, carbs_g=24.0,fat_g=0.2,  fiber_g=0.4),
    "banh_canh":      MacroNutrients(calories_kcal=130, protein_g=2.0, carbs_g=29.0,fat_g=0.3,  fiber_g=0.3),
    "hu_tieu":        MacroNutrients(calories_kcal=109, protein_g=2.0, carbs_g=24.0,fat_g=0.2,  fiber_g=0.4),
    "mien_dong":      MacroNutrients(calories_kcal=352, protein_g=0.2, carbs_g=86.0,fat_g=0.0,  fiber_g=0.8),
    "mi_trung":       MacroNutrients(calories_kcal=138, protein_g=5.0, carbs_g=25.0,fat_g=2.0,  fiber_g=0.8),
    "banh_trang":     MacroNutrients(calories_kcal=335, protein_g=2.5, carbs_g=81.0,fat_g=0.5,  fiber_g=0.5),
    "banh_da_cua":    MacroNutrients(calories_kcal=320, protein_g=5.0, carbs_g=73.0,fat_g=0.5,  fiber_g=0.3),
    "banh_hoi":       MacroNutrients(calories_kcal=115, protein_g=2.2, carbs_g=26.0,fat_g=0.2,  fiber_g=0.3),
    "bot_gao":        MacroNutrients(calories_kcal=366, protein_g=6.0, carbs_g=80.0,fat_g=0.6,  fiber_g=2.4),
    "bot_nang":       MacroNutrients(calories_kcal=357, protein_g=0.2, carbs_g=88.0,fat_g=0.0,  fiber_g=0.9),
    "bot_nep":        MacroNutrients(calories_kcal=362, protein_g=6.5, carbs_g=79.5,fat_g=0.5,  fiber_g=1.0),
    "bot_chien_xu":   MacroNutrients(calories_kcal=395, protein_g=13.5,carbs_g=72.0,fat_g=5.8,  fiber_g=4.0),
    "bot_banh_xeo":   MacroNutrients(calories_kcal=360, protein_g=5.0, carbs_g=79.0,fat_g=1.0,  fiber_g=1.5),
    "thit_ba_chi":    MacroNutrients(calories_kcal=518, protein_g=9.0, carbs_g=0.0, fat_g=53.0, fiber_g=0.0),
    "thit_nac_vai":   MacroNutrients(calories_kcal=216, protein_g=19.0,carbs_g=0.0, fat_g=15.0, fiber_g=0.0),
    "thit_nac_dam":   MacroNutrients(calories_kcal=242, protein_g=20.0,carbs_g=0.0, fat_g=17.0, fiber_g=0.0),
    "suon_non":       MacroNutrients(calories_kcal=321, protein_g=15.0,carbs_g=0.0, fat_g=28.0, fiber_g=0.0),
    "mong_gio":       MacroNutrients(calories_kcal=248, protein_g=17.0,carbs_g=0.0, fat_g=20.0, fiber_g=0.0),
    "da_heo":         MacroNutrients(calories_kcal=346, protein_g=20.0,carbs_g=0.0, fat_g=29.0, fiber_g=0.0),
    "tai_heo":        MacroNutrients(calories_kcal=176, protein_g=22.5,carbs_g=0.4, fat_g=9.0,  fiber_g=0.0),
    "long_heo":       MacroNutrients(calories_kcal=106, protein_g=16.0,carbs_g=0.0, fat_g=4.7,  fiber_g=0.0),
    "gio_song":       MacroNutrients(calories_kcal=265, protein_g=15.0,carbs_g=2.0, fat_g=22.0, fiber_g=0.0),
    "thit_bo_than":   MacroNutrients(calories_kcal=207, protein_g=26.0,carbs_g=0.0, fat_g=11.0, fiber_g=0.0),
    "bap_bo":         MacroNutrients(calories_kcal=180, protein_g=27.0,carbs_g=0.0, fat_g=7.0,  fiber_g=0.0),
    "nam_bo":         MacroNutrients(calories_kcal=258, protein_g=17.0,carbs_g=0.0, fat_g=21.0, fiber_g=0.0),
    "gan_bo":         MacroNutrients(calories_kcal=150, protein_g=28.0,carbs_g=0.0, fat_g=4.0,  fiber_g=0.0),
    "duoi_bo":        MacroNutrients(calories_kcal=263, protein_g=18.0,carbs_g=0.0, fat_g=21.0, fiber_g=0.0),
    "ga_ta":          MacroNutrients(calories_kcal=189, protein_g=20.0,carbs_g=0.0, fat_g=12.0, fiber_g=0.0),
    "vit":            MacroNutrients(calories_kcal=337, protein_g=19.0,carbs_g=0.0, fat_g=28.0, fiber_g=0.0),
    "ngan":           MacroNutrients(calories_kcal=220, protein_g=19.0,carbs_g=0.0, fat_g=15.0, fiber_g=0.0),
    "chim_bo_cau":    MacroNutrients(calories_kcal=294, protein_g=18.0,carbs_g=0.0, fat_g=24.0, fiber_g=0.0),
    "trung_ga":       MacroNutrients(calories_kcal=155, protein_g=13.0,carbs_g=1.1, fat_g=11.0, fiber_g=0.0),
    "trung_vit":      MacroNutrients(calories_kcal=185, protein_g=13.0,carbs_g=1.4, fat_g=14.0, fiber_g=0.0),
    "trung_cut":      MacroNutrients(calories_kcal=158, protein_g=13.1,carbs_g=0.4, fat_g=11.1, fiber_g=0.0),
    "trung_vit_lon":  MacroNutrients(calories_kcal=182, protein_g=13.6,carbs_g=6.0, fat_g=12.0, fiber_g=0.0),
    "trung_bac_thao": MacroNutrients(calories_kcal=170, protein_g=13.8,carbs_g=1.2, fat_g=12.5, fiber_g=0.0),
    "trung_muoi":     MacroNutrients(calories_kcal=203, protein_g=14.0,carbs_g=1.8, fat_g=16.0, fiber_g=0.0),
    "ca_loc":         MacroNutrients(calories_kcal=84,  protein_g=18.0,carbs_g=0.0, fat_g=0.8,  fiber_g=0.0),
    "ca_dieu_hong":   MacroNutrients(calories_kcal=96,  protein_g=20.0,carbs_g=0.0, fat_g=1.7,  fiber_g=0.0),
    "ca_ro":          MacroNutrients(calories_kcal=90,  protein_g=20.0,carbs_g=0.0, fat_g=1.2,  fiber_g=0.0),
    "ca_tre":         MacroNutrients(calories_kcal=144, protein_g=18.0,carbs_g=0.0, fat_g=8.0,  fiber_g=0.0),
    "ca_thu":         MacroNutrients(calories_kcal=205, protein_g=19.0,carbs_g=0.0, fat_g=14.0, fiber_g=0.0),
    "ca_ngu":         MacroNutrients(calories_kcal=144, protein_g=23.0,carbs_g=0.0, fat_g=6.0,  fiber_g=0.0),
    "ca_nuc":         MacroNutrients(calories_kcal=166, protein_g=20.0,carbs_g=0.0, fat_g=9.0,  fiber_g=0.0),
    "ca_bong":        MacroNutrients(calories_kcal=96,  protein_g=20.0,carbs_g=0.0, fat_g=1.5,  fiber_g=0.0),
    "tom_su":         MacroNutrients(calories_kcal=85,  protein_g=20.0,carbs_g=0.0, fat_g=0.6,  fiber_g=0.0),
    "tom_dat":        MacroNutrients(calories_kcal=99,  protein_g=21.0,carbs_g=0.0, fat_g=0.9,  fiber_g=0.0),
    "tom_the":        MacroNutrients(calories_kcal=99,  protein_g=21.0,carbs_g=0.0, fat_g=0.9,  fiber_g=0.0),
    "cua_dong":       MacroNutrients(calories_kcal=92,  protein_g=18.0,carbs_g=0.0, fat_g=1.8,  fiber_g=0.0),
    "cua_bien":       MacroNutrients(calories_kcal=97,  protein_g=18.0,carbs_g=0.0, fat_g=2.3,  fiber_g=0.0),
    "ghe":            MacroNutrients(calories_kcal=97,  protein_g=18.5,carbs_g=0.0, fat_g=2.0,  fiber_g=0.0),
    "muc_la":         MacroNutrients(calories_kcal=92,  protein_g=16.0,carbs_g=3.1, fat_g=1.4,  fiber_g=0.0),
    "muc_ong":        MacroNutrients(calories_kcal=92,  protein_g=16.0,carbs_g=3.1, fat_g=1.4,  fiber_g=0.0),
    "muc_trung":      MacroNutrients(calories_kcal=95,  protein_g=15.5,carbs_g=4.0, fat_g=1.5,  fiber_g=0.0),
    "ngheu":          MacroNutrients(calories_kcal=74,  protein_g=13.0,carbs_g=2.7, fat_g=1.0,  fiber_g=0.0),
    "so_huyet":       MacroNutrients(calories_kcal=80,  protein_g=14.0,carbs_g=4.0, fat_g=1.0,  fiber_g=0.0),
    "oc_buou":        MacroNutrients(calories_kcal=92,  protein_g=16.0,carbs_g=4.0, fat_g=1.4,  fiber_g=0.0),
    "hen":            MacroNutrients(calories_kcal=86,  protein_g=12.0,carbs_g=3.7, fat_g=2.2,  fiber_g=0.0),
    "luon":           MacroNutrients(calories_kcal=184, protein_g=18.0,carbs_g=0.0, fat_g=12.0, fiber_g=0.0),
    "dau_hu_trang":   MacroNutrients(calories_kcal=76,  protein_g=8.0, carbs_g=1.9, fat_g=4.8,  fiber_g=0.3),
    "dau_hu_chien":   MacroNutrients(calories_kcal=175, protein_g=12.0,carbs_g=4.0, fat_g=13.0, fiber_g=0.5),
    "tau_hu_ky":      MacroNutrients(calories_kcal=196, protein_g=17.0,carbs_g=7.0, fat_g=12.0, fiber_g=0.5),
    "hoa_hoi":        MacroNutrients(calories_kcal=337, protein_g=18.0,carbs_g=50.0,fat_g=16.0, fiber_g=15.0),
    "que_chi":        MacroNutrients(calories_kcal=247, protein_g=4.0, carbs_g=81.0,fat_g=1.2,  fiber_g=53.1),
    "thao_qua":       MacroNutrients(calories_kcal=311, protein_g=11.0,carbs_g=68.0,fat_g=7.0,  fiber_g=28.0),
    "hat_mui":        MacroNutrients(calories_kcal=298, protein_g=12.4,carbs_g=55.0,fat_g=17.8, fiber_g=41.9),
    "dinh_huong":     MacroNutrients(calories_kcal=274, protein_g=6.0, carbs_g=66.0,fat_g=13.0, fiber_g=34.2),
    "hat_mac_khen":   MacroNutrients(calories_kcal=285, protein_g=10.0,carbs_g=65.0,fat_g=8.0,  fiber_g=25.0),
    "hat_doi":        MacroNutrients(calories_kcal=280, protein_g=10.0,carbs_g=60.0,fat_g=8.0,  fiber_g=25.0),
    "dau_xanh":       MacroNutrients(calories_kcal=347, protein_g=23.9,carbs_g=62.6,fat_g=1.2,  fiber_g=16.3),
    "dau_phong":      MacroNutrients(calories_kcal=567, protein_g=25.8,carbs_g=16.1,fat_g=49.2, fiber_g=8.5),
    "me_vung":        MacroNutrients(calories_kcal=573, protein_g=17.7,carbs_g=23.5,fat_g=49.7, fiber_g=11.8),
    "hat_dieu":       MacroNutrients(calories_kcal=553, protein_g=18.2,carbs_g=30.2,fat_g=43.8, fiber_g=3.3),
    "me_qua":         MacroNutrients(calories_kcal=239, protein_g=2.8, carbs_g=62.5,fat_g=0.6,  fiber_g=5.1),
    "dua_thom":       MacroNutrients(calories_kcal=50,  protein_g=0.5, carbs_g=13.1,fat_g=0.1,  fiber_g=1.4),
    "xoai_xanh":      MacroNutrients(calories_kcal=60,  protein_g=0.8, carbs_g=15.0,fat_g=0.4,  fiber_g=1.6),
    "khe_chua":       MacroNutrients(calories_kcal=31,  protein_g=1.0, carbs_g=7.0, fat_g=0.3,  fiber_g=2.8),
    "chuoi_chat":     MacroNutrients(calories_kcal=89,  protein_g=1.1, carbs_g=22.8,fat_g=0.3,  fiber_g=2.6),
    "sung":           MacroNutrients(calories_kcal=74,  protein_g=0.8, carbs_g=19.2,fat_g=0.3,  fiber_g=2.9),
    "qua_sau":        MacroNutrients(calories_kcal=50,  protein_g=0.8, carbs_g=12.0,fat_g=0.2,  fiber_g=2.0),
    "muoi_hat":       MacroNutrients(calories_kcal=0,   protein_g=0.0, carbs_g=0.0, fat_g=0.0,  fiber_g=0.0),
    "muoi_ham":       MacroNutrients(calories_kcal=0,   protein_g=0.0, carbs_g=0.0, fat_g=0.0,  fiber_g=0.0),
    "duong_cat":      MacroNutrients(calories_kcal=387, protein_g=0.0, carbs_g=100.0,fat_g=0.0, fiber_g=0.0),
    "duong_phen":     MacroNutrients(calories_kcal=387, protein_g=0.0, carbs_g=100.0,fat_g=0.0, fiber_g=0.0),
    "duong_thot_not": MacroNutrients(calories_kcal=380, protein_g=0.0, carbs_g=98.0,fat_g=0.0,  fiber_g=0.0),
    "hat_nem":        MacroNutrients(calories_kcal=180, protein_g=15.0,carbs_g=25.0,fat_g=2.0,  fiber_g=0.0),
    "bot_ngot":       MacroNutrients(calories_kcal=0,   protein_g=0.0, carbs_g=0.0, fat_g=0.0,  fiber_g=0.0),
}
