"""
Remote AI inference client.

The AI service can forward images to an external model API using a Bearer token
or directly to Google's Gemini API.
"""
from __future__ import annotations

import base64
import io
import json
from typing import Any

import httpx

from app.core.config import settings
from app.core.logging import get_logger

logger = get_logger(__name__)


class InferenceClientError(RuntimeError):
    pass


async def analyze_image_via_gemini(image_bytes: bytes, filename: str, content_type: str) -> dict[str, Any]:
    """
    Send an image to the Google Gemini API directly and return the response
    structured matching the expected AIInferenceResponse schema.
    """
    if not settings.gemini_api_key:
        raise InferenceClientError("Gemini API key is not configured")

    image_b64 = base64.b64encode(image_bytes).decode("utf-8")
    mime_type = content_type or "image/jpeg"

    # Precise prompt instructing Gemini to analyze ingredients, suggest dishes, and build nutrition
    prompt = """
    Phân tích hình ảnh món ăn/nguyên liệu này và trả về JSON theo cấu trúc sau:
    {
      "api_version": "v1",
      "status": "done",
      "luong_tin_cay_chung": "độ tin cậy chung của phân tích (ví dụ: '92%')",
      "nguyen_lieu_tho_quet_duoc": [
        {
          "id_nguyen_lieu": "mã tự sinh duy nhất, ví dụ: 'raw_01'",
          "ten_nguyen_lieu": "tên nguyên liệu thô bằng tiếng Việt hiển thị, ví dụ: 'Ức gà tươi sống'",
          "ten_nguyen_lieu_ky_thuat": "mã kỹ thuật snake_case tiếng Việt không dấu, ví dụ: 'uc_ga'",
          "khoi_luong_uoc_tinh_g": ước tính khối lượng bằng gram (float),
          "do_chinh_xac_uoc_tinh": "độ chính xác ước tính (ví dụ: '95%')"
        }
      ],
      "danh_sach_mon_an_goi_y": [
        {
          "id_mon_an_goi_y": "mã tự sinh duy nhất, ví dụ: 'rec_01'",
          "ten_mon_an": "tên món ăn gợi ý bằng tiếng Việt, ví dụ: 'Ức gà áp chảo xào bông cải xanh'",
          "ten_mon_an_ky_thuat": "mã kỹ thuật snake_case tiếng Việt không dấu, ví dụ: 'uc_ga_ap_chao_xao_bong_cai_xanh'",
          "mo_ta_ngan": "mô tả ngắn về món ăn và cách làm sơ bộ",
          "do_kha_thi": "độ khả thi thực hiện (ví dụ: '95%')",
          "confidence": độ tin cậy của món ăn gợi ý (float từ 0.0 đến 1.0),
          "nguyen_lieu_su_dung": [
            {
              "ten": "tên nguyên liệu sử dụng, ví dụ: 'Ức gà'",
              "ten_ky_thuat": "mã kỹ thuật snake_case tiếng Việt không dấu, ví dụ: 'uc_ga'",
              "khoi_luong_g": khối lượng sử dụng bằng gram (float)
            }
          ],
          "thong_tin_dinh_duong_mon_an": {
            "tong_calories": tổng lượng calories kcal (float),
            "protein_g": lượng protein gram (float),
            "carbs_g": lượng carbohydrates gram (float),
            "fat_g": lượng fat gram (float),
            "fiber_g": lượng chất xơ gram (float)
          }
        }
      ]
    }
    Hãy chỉ trả về duy nhất chuỗi JSON hợp lệ khớp với cấu trúc trên. Không thêm markdown block (```json) hay bất kỳ văn bản giải thích nào khác.
    """

    payload = {
        "contents": [
            {
                "parts": [
                    {"text": prompt},
                    {
                        "inlineData": {
                            "mimeType": mime_type,
                            "data": image_b64
                        }
                    }
                ]
            }
        ],
        "generationConfig": {
            "responseMimeType": "application/json"
        }
    }

    url = f"https://generativelanguage.googleapis.com/v1beta/models/{settings.gemini_model}:generateContent?key={settings.gemini_api_key}"
    timeout = httpx.Timeout(settings.ai_api_timeout_seconds)

    async with httpx.AsyncClient(timeout=timeout) as client:
        resp = await client.post(url, json=payload)
        try:
            resp.raise_for_status()
        except httpx.HTTPStatusError as exc:
            logger.warning("gemini_api_http_error", status_code=resp.status_code, body=resp.text[:500])
            raise InferenceClientError(f"Gemini API request failed: {exc}") from exc

        data = resp.json()
        try:
            text_response = data["candidates"][0]["content"]["parts"][0]["text"]
            result = json.loads(text_response)

            # Ensure job_id and request_id are present, since they might not be generated by Gemini but are required by schema
            import uuid
            if "job_id" not in result or not result["job_id"]:
                result["job_id"] = str(uuid.uuid4())
            if "request_id" not in result or not result["request_id"]:
                result["request_id"] = str(uuid.uuid4())

            return result
        except (KeyError, IndexError, json.JSONDecodeError) as err:
            logger.error("gemini_response_parse_failed", error=str(err), raw_response=resp.text[:1000])
            raise InferenceClientError(f"Failed to parse Gemini response: {err}") from err


async def analyze_image(image_bytes: bytes, filename: str, content_type: str) -> dict[str, Any]:
    """
    Main entrypoint: analyzes the image using either the remote API or Gemini directly.
    """
    # Return mock response if explicitly configured or if no keys are set in development mode
    if settings.ai_provider == "mock" or (not settings.is_production and not settings.ai_api_key and not settings.gemini_api_key):
        logger.warning("ai_not_configured_dev_fallback_to_mock")
        import uuid
        return {
            "job_id": str(uuid.uuid4()),
            "request_id": str(uuid.uuid4()),
            "api_version": "v1",
            "status": "done",
            "processing_time_ms": 1234.5,
            "luong_tin_cay_chung": "92%",
            "nguyen_lieu_tho_quet_duoc": [
                {
                    "id_nguyen_lieu": "raw_01",
                    "ten_nguyen_lieu": "Ức gà tươi sống",
                    "ten_nguyen_lieu_ky_thuat": "uc_ga",
                    "khoi_luong_uoc_tinh_g": 250.0,
                    "do_chinh_xac_uoc_tinh": "95%"
                }
            ],
            "danh_sach_mon_an_goi_y": [
                {
                    "id_mon_an_goi_y": "rec_01",
                    "ten_mon_an": "Ức gà áp chảo xào bông cải xanh",
                    "ten_mon_an_ky_thuat": "uc_ga_ap_chao_xao_bong_cai_xanh",
                    "mo_ta_ngan": "Món ăn ngon và giàu dinh dưỡng tốt cho sức khỏe.",
                    "do_kha_thi": "95%",
                    "confidence": 0.95,
                    "nguyen_lieu_su_dung": [
                        {
                            "ten": "Ức gà",
                            "ten_ky_thuat": "uc_ga",
                            "khoi_luong_g": 250.0
                        }
                    ],
                    "thong_tin_dinh_duong_mon_an": {
                        "tong_calories": 320.0,
                        "protein_g": 55.2,
                        "carbs_g": 11.5,
                        "fat_g": 7.3,
                        "fiber_g": 3.8
                    }
                }
            ]
        }

    if settings.ai_provider == "gemini":
        return await analyze_image_via_gemini(image_bytes, filename, content_type)

    if not settings.ai_api_base_url or not settings.ai_api_key:
        raise InferenceClientError("AI inference API is not configured")

    timeout = httpx.Timeout(settings.ai_api_timeout_seconds)
    headers = {"Authorization": f"Bearer {settings.ai_api_key}"}
    files = {"image": (filename or "image.jpg", io.BytesIO(image_bytes), content_type or "image/jpeg")}

    async with httpx.AsyncClient(timeout=timeout, headers=headers) as client:
        resp = await client.post(f"{settings.ai_api_base_url.rstrip('/')}/analyze", files=files)
        try:
            resp.raise_for_status()
        except httpx.HTTPStatusError as exc:
            logger.warning("ai_inference_http_error", status_code=resp.status_code, body=resp.text[:500])
            raise InferenceClientError(str(exc)) from exc
        return resp.json()
