"""Canonical label mapping between technical keys and Vietnamese display labels."""
from __future__ import annotations

from typing import Dict, Tuple

LABEL_MAP: Dict[str, Tuple[str, str]] = {
    "uc_ga": ("uc_ga", "Ức gà tươi sống"),
    "bong_cai_xanh": ("bong_cai_xanh", "Bông cải xanh (Súp lơ)"),
    "thit_ba_chi": ("thit_ba_chi", "Thịt ba chỉ"),
    "ca_chua": ("ca_chua", "Cà chua"),
    "rau_muong": ("rau_muong", "Rau muống"),
    "dau_oliu": ("dau_oliu", "Dầu ô liu"),

    # --- 1. Gia vị & Nước chấm bản sắc ---
    "nuoc_mam": ("nuoc_mam", "Nước mắm"),
    "mam_tom": ("mam_tom", "Mắm tôm"),
    "mam_ruoc": ("mam_ruoc", "Mắm ruốc"),
    "mam_nem": ("mam_nem", "Mắm nêm"),
    "mam_ba_khia": ("mam_ba_khia", "Mắm ba khía"),
    "mam_ca": ("mam_ca", "Mắm cá (sặc/linh)"),
    "tuong_hot_ban": ("tuong_hot_ban", "Tương hột / Tương bần"),
    "giam_bong_me": ("giam_bong_me", "Giấm bỗng / Giấm mẻ"),
    "chanh": ("chanh", "Quả chanh"),
    "quat_tac": ("quat_tac", "Quả quất (tắc)"),
    "khe_chua": ("khe_chua", "Khế chua"),
    "sau": ("sau", "Quả sấu"),
    "doc": ("doc", "Quả dọc"),
    "me": ("me", "Quả me"),
    "tai_chua": ("tai_chua", "Tai chua"),

    # --- 2. Rau thơm & Thảo mộc ---
    "hanh": ("hanh", "Hành củ"),
    "he": ("he", "Lá hẹ"),
    "toi": ("toi", "Tỏi"),
    "sa": ("sa", "Sả"),
    "gung": ("gung", "Gừng"),
    "nghe": ("nghe", "Nghệ"),
    "rieng": ("rieng", "Riềng"),
    "ngo_ri": ("ngo_ri", "Rau mùi (Ngò rí)"),
    "hanh_la": ("hanh_la", "Hành lá"),
    "hung_que": ("hung_que", "Húng quế (Húng chó)"),
    "ngo_gai": ("ngo_gai", "Ngò gai (Mùi tàu)"),
    "rau_ram": ("rau_ram", "Rau răm"),
    "kinh_gioi": ("kinh_gioi", "Rau kinh giới"),
    "tia_to": ("tia_to", "Rau tía tô"),
    "rau_ngo": ("rau_ngo", "Rau ngổ (Ngò ôm)"),
    "la_lot": ("la_lot", "Lá lốt"),

    # --- 3. Các loại Rau, Củ, Quả & Hoa nấu ăn ---
    "rau_ngot": ("rau_ngot", "Rau ngót"),
    "rau_mong_toi": ("rau_mong_toi", "Rau mồng tơi"),
    "cai_xanh": ("cai_xanh", "Cải xanh"),
    "cai_cuc": ("cai_cuc", "Cải cúc (Tần ô)"),
    "rau_den": ("rau_den", "Rau dền"),
    "rau_dang": ("rau_dang", "Rau đắng"),
    "rau_toai": ("rau_toai", "Rau toại"),
    "rau_mop": ("rau_mop", "Rau móp"),
    "rau_cang_cua": ("rau_cang_cua", "Rau càng cua"),
    "hoa_thien_ly": ("hoa_thien_ly", "Hoa thiên lý"),
    "bong_bi": ("bong_bi", "Bông bí"),
    "bong_dien_dien": ("bong_dien_dien", "Bông điên điển"),
    "bong_sung": ("bong_sung", "Bông súng"),
    "su_hao": ("su_hao", "Su hào"),
    "bi_xanh": ("bi_xanh", "Bí đao (Bí xanh)"),
    "muop_huong": ("muop_huong", "Mướp hương"),
    "bau": ("bau", "Quả bầu"),
    "kho_qua": ("kho_qua", "Khổ qua (Mướp đắng)"),
    "mang_tre": ("mang_tre", "Măng tre (Tươi/Khô)"),
    "ca_rot": ("ca_rot", "Cà rốt"),
    "khoai_tay": ("khoai_tay", "Khoai tây"),
    "bi_do": ("bi_do", "Bí đỏ"),
    "bap_cai": ("bap_cai", "Bắp cải"),
    "cai_thao": ("cai_thao", "Cải thảo"),
    "cai_ngot": ("cai_ngot", "Cải ngọt"),
    "xa_lach": ("xa_lach", "Xà lách"),
    "gia_do": ("gia_do", "Giá đỗ"),
    "dua_leo": ("dua_leo", "Dưa leo (Dưa chuột)"),
    "hanh_tay": ("hanh_tay", "Hành tây"),
    "ot": ("ot", "Ớt"),

    # --- 4. Tinh bột: Gạo & Các chế phẩm từ Gạo ---
    "gao_te": ("gao_te", "Gạo tẻ"),
    "gao_nep": ("gao_nep", "Gạo nếp"),
    "bun": ("bun", "Bún tươi"),
    "pho": ("pho", "Bánh phở"),
    "hu_tieu": ("hu_tieu", "Hủ tiếu"),
    "banh_da_do": ("banh_da_do", "Bánh đa đỏ (Hải Phòng)"),
    "mien_dong": ("mien_dong", "Miến dong"),
    "banh_trang": ("banh_trang", "Bánh tráng"),
    "bot_gao": ("bot_gao", "Bột gạo"),
    "bot_nang": ("bot_nang", "Bột năng"),
    "bot_nep": ("bot_nep", "Bột nếp"),
    "bot_cu_nang": ("bot_cu_nang", "Bột củ năng"),
    "gao_lut": ("gao_lut", "Gạo lứt"),
    "khoai_lang": ("khoai_lang", "Khoai lang"),
    "banh_mi": ("banh_mi", "Bánh mì"),
    "ngo": ("ngo", "Ngô (Bắp)"),

    # --- 5. Protein: Thịt, Hải sản & Đồ khô ---
    "thit_heo": ("thit_heo", "Thịt heo (Thịt lợn)"),
    "thit_bo": ("thit_bo", "Thịt bò"),
    "thit_ga": ("thit_ga", "Thịt gà"),
    "thit_vit": ("thit_vit", "Thịt vịt"),
    "thit_ngan": ("thit_ngan", "Thịt ngan"),
    "ca_loc": ("ca_loc", "Cá lóc (Cá quả)"),
    "ca_tre": ("ca_tre", "Cá trê"),
    "ca_ro": ("ca_ro", "Cá rô"),
    "tom_dong": ("tom_dong", "Tôm đồng"),
    "cua_dong": ("cua_dong", "Cua đồng (làm riêu cua)"),
    "luon": ("luon", "Thịt lươn"),
    "ech": ("ech", "Thịt ếch"),
    "ngheu": ("ngheu", "Nghêu (Ngao)"),
    "so": ("so", "Các loại sò"),
    "oc": ("oc", "Các loại ốc"),
    "hen": ("hen", "Hến"),
    "tom_kho": ("tom_kho", "Tôm khô"),
    "muc_kho": ("muc_kho", "Mực khô"),
    "ca_kho": ("ca_kho", "Cá khô (sặc/dứa)"),
    "lap_xuong": ("lap_xuong", "Lạp xưởng"),
    "dau_hu": ("dau_hu", "Đậu hũ (Đậu phụ)"),
    "tao_pho": ("tao_pho", "Tào phớ"),

    # --- 6. Các loại hạt & Nguyên liệu nấu chè/bánh ngọt ---
    "hat_tieu": ("hat_tieu", "Hạt tiêu"),
    "hat_dieu": ("hat_dieu", "Hạt điều"),
    "dau_phong": ("dau_phong", "Đậu phộng (Lạc)"),
    "dau_xanh": ("dau_xanh", "Đậu xanh"),
    "dau_den": ("dau_den", "Đậu đen"),
    "dau_do": ("dau_do", "Đậu đỏ"),
    "nuoc_cot_dua": ("nuoc_cot_dua", "Nước cốt dừa"),

    "unknown": ("unknown", "Không xác định"),
}


def map_label(label_key: str) -> tuple[str, str]:
    return LABEL_MAP.get(label_key, (label_key, label_key.replace("_", " ").title()))
